# Generated by Django 5.2.16 on 2026-08-02 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=160)),
                ('qualification', models.CharField(max_length=160)),
                ('field_of_study', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('year_completed', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Education',
                'ordering': ['order', '-year_completed'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=160)),
                ('title', models.CharField(max_length=160)),
                ('location', models.CharField(max_length=120)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('proficiency', models.CharField(choices=[('NATIVE', 'Native'), ('FLUENT', 'Fluent'), ('PROFESSIONAL', 'Professional'), ('CONVERSATIONAL', 'Conversational'), ('BASIC', 'Basic')], max_length=20)),
                ('notes', models.CharField(blank=True, max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('headline', models.CharField(help_text='e.g. "AI Solutions Delivery Manager"', max_length=160)),
                ('tagline', models.CharField(help_text='One-line positioning statement', max_length=240)),
                ('introduction', models.TextField(help_text='2-3 paragraph introduction')),
                ('location', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=40)),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='profile/')),
                ('cv_file', models.FileField(blank=True, upload_to='cv/')),
                ('years_experience', models.PositiveIntegerField()),
                ('open_to_work', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('situation', models.TextField()),
                ('task', models.TextField()),
                ('action', models.TextField()),
                ('result', models.TextField()),
                ('headline_metric', models.CharField(blank=True, help_text='"60% fewer incidents"', max_length=80)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_studies', to='portfolio.experience')),
            ],
            options={
                'verbose_name_plural': 'Case studies',
                'ordering': ['order', '-date_completed'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('metric_value', models.CharField(blank=True, help_text='"60%", "RM 1.2M", "600+"', max_length=40)),
                ('metric_label', models.CharField(blank=True, help_text='"incident reduction"', max_length=80)),
                ('is_headline', models.BooleanField(default=False, help_text='Surface on portfolio hero')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='portfolio.experience')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
