# Generated by Django 5.2.16 on 2026-08-04 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(choices=[('AI_DELIVERY', 'AI Delivery'), ('SMART_SYSTEMS', 'Smart Systems'), ('COMPUTER_VISION', 'Computer Vision'), ('IOT_ROBOTICS', 'IoT & Robotics'), ('DATA_ANALYTICS', 'Data Analytics'), ('LEADERSHIP', 'Leadership'), ('CLOUD', 'Cloud'), ('GOVERNANCE', 'Governance')], default='AI_DELIVERY', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Core expertise',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('abbreviation', models.CharField(help_text='Short label shown in the badge, e.g. "Py", "AWS"', max_length=6)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tools & technologies',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='casestudy',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='case-studies/'),
        ),
    ]
