# Generated by Django 5.2.16 on 2026-08-04 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_coreexpertise_techtool_casestudy_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='tech_tags',
            field=models.CharField(blank=True, help_text='Comma-separated, e.g. "Python, OpenCV, AWS"', max_length=200),
        ),
        migrations.AlterField(
            model_name='coreexpertise',
            name='icon',
            field=models.CharField(choices=[('AI_DELIVERY', 'AI Delivery'), ('SMART_SYSTEMS', 'Smart Systems'), ('COMPUTER_VISION', 'Computer Vision'), ('IOT_ROBOTICS', 'IoT & Robotics'), ('DATA_ANALYTICS', 'Data Analytics'), ('LEADERSHIP', 'Leadership'), ('CLOUD', 'Cloud'), ('GOVERNANCE', 'Governance'), ('MACHINE_LEARNING', 'Machine Learning'), ('DIGITAL_HUMAN', 'Digital Human'), ('RAG', 'RAG'), ('PROJECT_MANAGEMENT', 'Project Management'), ('ENTERPRISE_AI', 'Enterprise AI')], default='AI_DELIVERY', max_length=20),
        ),
    ]
