# Generated by Django 5.2.16 on 2026-08-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_casestudy_tech_tags_alter_coreexpertise_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='techtool',
            name='icon',
            field=models.ImageField(blank=True, help_text="Optional — upload the vendor's real logo for a pixel-perfect icon", upload_to='tools/'),
        ),
        migrations.AddField(
            model_name='techtool',
            name='icon_key',
            field=models.CharField(choices=[('PYTHON', 'Python'), ('FASTAPI', 'FastAPI'), ('REACT', 'React'), ('TENSORFLOW', 'TensorFlow'), ('PYTORCH', 'PyTorch'), ('OPENCV', 'OpenCV'), ('LANGCHAIN', 'LangChain'), ('OPENAI', 'OpenAI'), ('CHROMADB', 'ChromaDB'), ('AWS', 'AWS'), ('AZURE', 'Azure'), ('DOCKER', 'Docker'), ('POSTGRESQL', 'PostgreSQL'), ('MONGODB', 'MongoDB'), ('GIT', 'Git'), ('LINUX', 'Linux'), ('GENERIC', 'Generic')], default='GENERIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='techtool',
            name='abbreviation',
            field=models.CharField(help_text='Fallback label if no icon matches, e.g. "Py", "AWS"', max_length=6),
        ),
    ]
