# Generated by Django 5.2.16 on 2026-08-02 10:55

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_title', models.CharField(max_length=160)),
                ('target_title', models.CharField(max_length=160)),
                ('current_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='RM', max_length=8)),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Career objective',
                'verbose_name_plural': 'Career objective',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('STUDYING', 'Studying'), ('BOOKED', 'Booked'), ('EARNED', 'Earned'), ('DEFERRED', 'Deferred'), ('ABANDONED', 'Abandoned')], default='PLANNED', max_length=12)),
                ('priority', models.PositiveSmallIntegerField(default=1)),
                ('planned_hours', models.PositiveIntegerField(default=0)),
                ('cost_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cost_currency', models.CharField(default='USD', max_length=8)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('earned_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=120)),
                ('credential_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('show_on_portfolio', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='Pillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=1, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('weight', models.PositiveSmallIntegerField(help_text='Percent weight, all pillars must total 100')),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SkillDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('HIGHEST', 'Highest'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider', models.CharField(max_length=120)),
                ('tier', models.CharField(choices=[('CERTIFICATION', 'Certification'), ('TECHNICAL', 'Technical'), ('LEADERSHIP', 'Leadership')], max_length=14)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('COMPLETE', 'Complete'), ('DROPPED', 'Dropped')], default='NOT_STARTED', max_length=12)),
                ('planned_hours', models.PositiveIntegerField(default=0)),
                ('url', models.URLField(blank=True)),
                ('is_free', models.BooleanField(default=True, help_text='Covered by Coursera Plus / LinkedIn Learning')),
                ('start_month', models.DateField(blank=True, help_text='Use the 1st of the month', null=True)),
                ('target_month', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('application_commitment', models.TextField(blank=True, help_text='The "use it at work" pairing')),
                ('application_done', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='tracker.certification')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='tracker.skilldomain')),
            ],
            options={
                'ordering': ['tier', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('theme', models.CharField(help_text='"Foundations", "First certification"', max_length=200)),
                ('target_hours', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETE', 'Complete'), ('SLIPPED', 'Slipped')], default='PLANNED', max_length=8)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment', models.TextField()),
                ('done_when', models.CharField(max_length=300)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='tracker.monthlyplan')),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tracker.pillar')),
            ],
            options={
                'ordering': ['plan__year', 'plan__month', 'order'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='A1, B3, C2...', max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('target', models.CharField(max_length=200)),
                ('verified_by', models.CharField(blank=True, max_length=200)),
                ('period', models.CharField(choices=[('YEARLY', 'Yearly'), ('MONTHLY', 'Monthly')], max_length=7)),
                ('period_year', models.PositiveIntegerField()),
                ('period_month', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('ON_TRACK', 'On track'), ('AT_RISK', 'At risk'), ('BEHIND', 'Behind'), ('COMPLETE', 'Complete')], default='NOT_STARTED', max_length=12)),
                ('target_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kpis', to='tracker.pillar')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
                'ordering': ['pillar__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('current_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('target_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('baseline_level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('why_it_matters', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='tracker.skilldomain')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='certification',
            name='domains',
            field=models.ManyToManyField(blank=True, related_name='certifications', to='tracker.skilldomain'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=datetime.date.today)),
                ('activity_type', models.CharField(choices=[('STUDY', 'Study'), ('EXAM', 'Exam'), ('APPLICATION', 'Application'), ('PRACTICE', 'Practice'), ('WORK_APPLICATION', 'Work application'), ('NETWORKING', 'Networking'), ('CONTENT', 'Content'), ('INTERVIEW', 'Interview'), ('REVIEW', 'Review'), ('MILESTONE', 'Milestone'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_milestone', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tracker.certification')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tracker.course')),
                ('kpi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='tracker.kpi')),
                ('skill_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.skilldomain')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
