# Generated by Django 5.2.16 on 2026-08-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVDownloadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_time', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('visitor_ip', models.GenericIPAddressField()),
                ('country', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('browser', models.CharField(blank=True, max_length=80)),
                ('device', models.CharField(choices=[('DESKTOP', 'Desktop'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('cv_version', models.CharField(blank=True, help_text='Filename of the CV at download time', max_length=200)),
                ('download_source', models.CharField(blank=True, help_text='Which button/page triggered the download', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-download_time'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(db_index=True)),
                ('last_seen', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('country', models.CharField(blank=True, db_index=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('timezone', models.CharField(blank=True, max_length=60)),
                ('browser', models.CharField(blank=True, max_length=80)),
                ('operating_system', models.CharField(blank=True, max_length=80)),
                ('device', models.CharField(choices=[('DESKTOP', 'Desktop'), ('MOBILE', 'Mobile'), ('TABLET', 'Tablet'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=10)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('referral_source', models.CharField(choices=[('DIRECT', 'Direct'), ('GOOGLE', 'Google'), ('LINKEDIN', 'LinkedIn'), ('GITHUB', 'GitHub'), ('OTHER', 'Other')], db_index=True, default='DIRECT', max_length=10)),
                ('landing_page', models.CharField(blank=True, max_length=300)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-visit_time'],
                'indexes': [models.Index(fields=['visit_time', 'device'], name='tracker_vis_visit_t_7d8fa8_idx')],
            },
        ),
    ]
